source 'https://rubygems.org'

gem 'rake'
gem 'ruboty'
gem 'ruboty-slack_rtm'
gem 'ruboty-astral_zatsudan', :git=> 'https://github.com/itiya/ruboty-astral_zatsudan.git'
gem 'ruboty-astral_todoist', :git=> 'https://github.com/itiya/ruboty-astral_todoist.git'
gem 'ruboty-cron'
gem 'ruboty-delay'
gem 'ruboty-alias'
gem 'ruboty-redis'
